### ISSUE TITLE
Modify dataset/TEXT files to XML files

### ISSUE THREAD

**Issue by leesju0103** [jihooni0914/OSSP_Team13#13]
**Describe the bug**
장소 카드 아래 역 이름과 해쉬태그 나오는 부분을 수정하면서 .txt 파일들을 .xml로 바꿔야 할 것 같습니다.

**To Reproduce**
1.  luvway 웹페이지에 들어갑니다.
2. 하트가 그려진 카드를 누르면 랜덤으로 지하철역 카드가 뽑힙니다.
3. txt 파일을 읽어들이면서 자체 html로 생성되어 css가 적용되지 않는 문제가 발생합니다.

**Expected behavior**
카드가 랜덤으로 뽑힌 후, 카드 아래 지하철역이 뜨고 그 역을 설명하는 해쉬태그가 떠야 합니다.
기존에 있던 텍스트 파일을 모두 xml 파일로 바꿔주면 해결할 수 있을 것 같습니다.

**Screenshots**
![image](https://user-images.githubusercontent.com/104543271/205265676-2736ec34-0eed-4139-86a5-6ba26c8005df.png)
사진의 양식을 참고하여 1~33번 사진 모두 바꿔주면 됩니다.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jihooni0914** [comment]
xml 파일 추가 및 반영하였습니다.

**Comment by leesju0103** [comment]
감사합니다
