### ISSUE TITLE
Text files for dating places do not contain station names.

### ISSUE THREAD

**Issue by leesju0103** [jihooni0914/OSSP_Team13#9]
**Describe the bug**
화면을 실행하고 카드를 뒤집었을 때, 각 장소에 관련된 해쉬태그와 함께 역 이름도 같이 나와야 하는데 역 이름이 보이지 않습니다. 1~17번 카드에 대한 텍스트에 역 이름을 포함해야 할 것 같습니다.

**To Reproduce**
1. luvway 웹페이지에 들어간다.
2. 카드가 랜덤으로 뜰 때 1번부터 17번에 해당하는 장소면 역 이름이 뜨지 않는 에러가 발생한다.

**Expected behavior**
카드가 랜덤으로 뽑힐 때, 카드 사진 밑 제일 왼쪽 해쉬태그에 역 이름이 나와야 한다.

**Screenshots**
![subway](https://user-images.githubusercontent.com/104543271/205249072-c8e38950-dfb0-4ddc-82a5-615005fe7636.JPG)
1번~17번에 해당하는 장소도 역 이름 해쉬태그가 뜨도록 수정해주세요.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chan-2** [comment]
제가 추가해서 풀리퀘 넣을게요~~~

**Comment by leesju0103** [comment]
송찬님 수정하신 파일들 git으로 올리는 과정에서 에러 뜨셔서 제가 대신 올리겠습니다!!
